### ISSUE TITLE
Typo in setup.py project url

### ISSUE THREAD

**Issue by Whenning42** [jpmanson/llm_templates#1]
Thanks for the really cool library, it looks like it does exactly what I need and I'm excited to have found it.

One issue I noticed, is that the project homepage link in pypi throws a 404. I think it's because setup.py lists the url as 'url="https://github.com/jpmanson/llm-templates', with a hyphen, but this repo is named with an underscore.

**Comment by jpmanson** [comment]
Hi William! Thanks for your comments. Now it's fixed!
